### ISSUE TITLE
The converter is not robust against markup errors within the MediaWiki dump

### ISSUE THREAD

**Issue by w4tsn** [peterjc/mediawiki_to_git_md#29] opened 2018-03-29 16:54 UTC
When processing a dump that contains a markup error such as `[[Category: Something]` instead of `[[Category: Something]]` the script gets stuck.

**Comment by peterjc** [comment] 2018-03-30 11:01
Would you be happy with the problem line being removed before calling pandoc? If so, adding a try/except somewhere here should be the right place (inside function ``cleanup_mediawiki``):

https://github.com/peterjc/mediawiki_to_git_md/blob/1ad6868c21e8f10a72574326682345495b6a899b/convert.py#L177

**Comment by w4tsn** [comment] 2018-03-30 11:45
I would expect to either "auto-correct" such an error (which would be kind of hard) or simply skipping but without causing the overall process to fail. Together with something like an error message in the summery at the end indicating that something could not be processed because of markup errors, so I can go back and potentially fix them.

**Comment by peterjc** [comment] 2018-03-30 12:00
Yes. A message to stderr would seem sensible. Do you want to work on this?

**Comment by w4tsn** [comment] 2018-03-30 12:07
Let me look into it this weekend, but no promises :)

**Comment by milahu** [comment] 2023-07-22 16:01
duplicate of #4 

ideally pandoc should render the exact same result as mediawiki. if pandoc cannot do that, we should use something else... for example, run the original PHP renderer in a python subprocess, then feed the rendered HTML to pandoc to generate markdown.

possible solutions:
https://github.com/wikimedia/mediawiki/blob/master/includes/parser/Parser.php - the old parser of mediawiki, written in PHP
https://github.com/wikimedia/mediawiki-services-parsoid - bidirectional parser between wikitext and HTML5, the new parser of mediawiki, written in JavaScript and PHP
https://github.com/5j9/wikitextparser - A Python library to parse MediaWiki WikiText
https://github.com/TrueBrain/wikitexthtml - Library to render WikiText to HTML, written in Python
https://github.com/tatuylonen/wikitextprocessor - Python package for WikiMedia dump processing (Wiktionary, Wikipedia etc). Wikitext parsing, template expansion, Lua module execution.
https://github.com/tatuylonen/wiktextract - Wiktionary dump file parser and multilingual data extractor, "this tool expands templates and Lua macros in Wiktionary. That enables much more accurate rendering"

**Comment by peterjc** [comment] 2023-07-22 18:13
I wonder if any of those tools would be significantly more robust to MediaWiki markup errors?

**Comment by peterjc** [comment] 2024-02-05 14:02
I think I found another gotcha with MediaWiki errors - when the file can't be converted to Markdown by pandoc, I currently skip the revision. Usually the original author immediately follows up with another revision to fix things, so this is fine. However, if not, the two sets of changes get mixed under the second author. I suspect this is complicating the user blocking functionality too.

I'm wondering now if it would be simpler to do this:

* Parse the XML dump,
  * Save every revision as a MediaWiki file and commit that in git
* Convert the final revision from MediaWiki to Markdown with pandoc as one large commit

This captures the page history more closely, and should also be significantly faster - far fewer calls to pandoc, and no git history cleanup to drop empty commits (originally done for the corner case where the MediaWiki changed but not the Markdown).

**Closed** 2024-02-07 17:05 UTC
